### PR TITLE
Add physio data

### PR DESCRIPTION
**Pull request by me-pic**
Add segmented raw physio data (PPG, ECG, EDA, RESP, TTL channels):
- tsv.gz files (timeseries)
- json sidecar (column names, sampling rate, start time)

### CODE REVIEW

**Comment by bpinsard** [comment]
To maximize BIDS compliance we should add a top-level `_physio.json`  file in each dataset with :

- [Manufacturer](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.Manufacturer)	RECOMMENDED	[string](https://www.w3schools.com/js/js_json_datatypes.asp)	Manufacturer of the equipment that produced the measurements.
- [ManufacturersModelName](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.ManufacturersModelName)	RECOMMENDED	[string](https://www.w3schools.com/js/js_json_datatypes.asp)	Manufacturer's model name of the equipment that produced the measurements.
- [SoftwareVersions](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.SoftwareVersions)	RECOMMENDED	[string](https://www.w3schools.com/js/js_json_datatypes.asp)	Manufacturer's designation of software version of the equipment that produced the measurements.
- [DeviceSerialNumber](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.DeviceSerialNumber)	RECOMMENDED	[string](https://www.w3schools.com/js/js_json_datatypes.asp)	The serial number of the equipment that produced the measurements. A pseudonym can also be used to prevent the equipment from being identifiable, so long as each pseudonym is unique within the dataset.

Biopac
MP160
Acknowledge xx.yy 
SerialNumber -> to be looked up downstairs if not in the acq files headers.


Also add more verbose columns descriptions ( such as describing ECG or EDA or PPG electrode types/ placement on the body/ signal-specific amplifier module... and specifying units if we can have it)  with additional fields as in this example in the spec:

```
{
    "SamplingFrequency": 100.0,
    "StartTime": -22.345,
    "Columns": ["cardiac", "respiratory", "trigger"],
    "Manufacturer": "Brain Research Equipment ltd.",
    "cardiac": {
        "Description": "continuous pulse measurement",
        "Units": "mV"
        },
    "respiratory": {
        "Description": "continuous measurements by respiration belt",
        "Units": "mV"
        },
    "trigger": {
        "Description": "continuous measurement of the scanner trigger signal"
        }
}
```

**Comment by me-pic** [comment]
For the columns name + description, it is not possible to comply to the BIDS standards because they actually do not account for different type of cardiac signals (i.e. PPG vs ECG). Also, they don't provide a standard column name for EDA...

**Comment by bpinsard** [comment]
IIUC, these are the column name so for us:
```
    "Columns": [
        "time",
        "EDA",
        "PPG",
        "ECG",
        "TTL",
        "RSP"
    ]
```

which should have a top-level json with something like: 

```
{
...
"EDA": { 
       "Description": "continuous skin conductance measure",
        "Units": "AU"},
"PPG": {       "Description": "continuous pulse measurement",
        "Units": "whatever"} 
}

```

BTW: why do we have a column "time".
Can't  we just use SamplingFrequency+StartTime to determine the time relative to fMRI? 
If that's a column with a fixed increment (of 1/SamplingFrequency s) that's a lot of data for nothing.

**Comment by lunebellec** [comment]
My 2 cents on the issue of the time column: it is negligible in terms of data size, and easier to parse for users than some kind of meta-data start time + sampling time. If we end up dropping frames as part of preprocessing, this format can also accomodate irregular grids. Is it something that is covered by the BIDS extension?

**Comment by bpinsard** [comment]
@all-contributors please add @me-pic for data preparation

**Pull request merged**
